# -*- coding: utf-8 -*-
"""01_cctv&population_2021_08_13

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nk_bAS2hBAIbrUZG1g-o4lhE3fABkJ-y
"""

!apt-get update
!apt-get install -y fonts-nanum
!fc-cache -fv
!rm ~/.cache/matplotlib -rf

import matplotlib as mpl
import matplotlib.pyplot as plt

mpl.rcParams['axes.unicode_minus'] = False

plt.rc('font',family='NanumBarunCothic')

import warnings
warnings.filterwarnings('ignore')

!ls -l

import pandas as pd

SDF = pd.read_csv('seoulCCTV.csv',encoding = 'utf-8')

SDF.head()

SDF.columns

SDF.rename(columns= {SDF.columns[0] : '구별'}, inplace = True)

SDF.head()

SDF.sort_values(by = '소계', ascending = True).head(10)

SDF.sort_values(by = '소계', ascending = False).head(10)

SDF['최근증가율'] = ((SDF['2016년']+SDF['2015년']+SDF['2014년'])/SDF['2013년도 이전']) * 100

SDF.sort_values(by = '최근증가율', ascending = False).head(10)

"""# 3.seoulPopulation"""

import pandas as pd

SDFP = pd.read_excel('seoulPopulation.xls', header =2,usecols='B,D,G,J,N') 

SDFP.head()

SDFP.tail()

SDFP.rename(columns= {SDFP.columns[0] : '구별', SDFP.columns[1] : '총인구', SDFP.columns[2] : '한국인',SDFP.columns[3] : '외국인',SDFP.columns[4] : '고령자'}, inplace=True)

SDFP.head()

SDFP.drop([0], inplace= True)

SDFP.head()

SDFP.tail()

SDFP['구별'].unique()

SDFP.drop([26], inplace= True)

SDFP.tail()

SDFP['외국인비율'] = SDFP['외국인']/SDFP['총인구']*100
SDFP['고령자비율'] = SDFP['고령자']/SDFP['총인구']*100

SDFP.head()

SDFP.sort_values(by='외국인', ascending = False).head(10)
SDFP.sort_values(by='총인구', ascending = False).head(10)

