# -*- coding: utf-8 -*-
"""01_notExercise_2021_08_13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wsNfUux__xU6VA-u9fFL9IfpNn1k4Nfc
"""

#운동하지 않는 이유 통계
#data.seoul.go.kr

!apt-get update
!apt-get install -y fonts-nanum
!fc-cache -fv
!rm ~/.cache/matplotlib -rf

import matplotlib as mpl
import matplotlib.pyplot as plt

mpl.rcParams['axes.unicode_minus'] = False

plt.rc('font',family='NanumBarunCothic')

import warnings
warnings.filterwarnings('ignore')

!ls -l

import pandas as pd

df = pd.read_excel('notExercise.xls')

df.head()

df.drop(columns= '기간', inplace= True)

#끝 데이터
df.tail()

df['대분류'][23:]
#목차 아래 첫번째 데이터 부터 0으로 지정됨.

#row 삭제
df.drop(index= range(23,53), inplace=True)

df.tail()

df

df_Gender = df[df['대분류'] == '성별'].copy()

df_Gender

df_Gender.drop(columns='대분류', inplace=True)

df_Gender

df_Gender.set_index('분류', inplace=True)
df_Gender

import matplotlib.pyplot as plt

figure, ax = plt.subplots(2,2,figsize = (10,10))

df_Gender['운동을 할 충분한 시간이 없어서'].plot.pie(explode = [0,0.02], ax = ax[0][0],autopct = '%1.1f%%')

ax[0][0].set_title('운동을 할 충분한 시간이 없어서')
ax[0][0].set_ylabel('')


df_Gender['함께 운동을 할 사람이 없어서'].plot.pie(explode = [0,0.02], ax = ax[0][1],autopct = '%1.1f%%')

ax[0][1].set_title('함께 운동을 할 사람이 없어서')
ax[0][1].set_ylabel('')


df_Gender['운동을 싫어해서'].plot.pie(explode = [0,0.02], ax = ax[1][0],autopct = '%1.1f%%')

ax[1][0].set_title('운동을 싫어해서')
ax[1][0].set_ylabel('')


df_Gender['운동을 할 만한 장소가 없어서'].plot.pie(explode = [0,0.02], ax = ax[1][1],autopct = '%1.1f%%')

ax[1][1].set_title('운동을 싫어해서')
ax[1][1].set_ylabel('')




plt.show()

#연령별

df_Ages = df[df['대분류']]